name: eq_parser
description: A lightweight and fast mathematical equation parser with support for functions and variables.
version: 1.0.1
repository: https://github.com/projectitis/eq_parser.git

environment:
  sdk: ^3.2.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
