name: eq_parser
description: A lightweight and fast mathematical equation parser with support for functions and variables.
version: 1.0.3
repository: https://github.com/projectitis/eq_parser.git

environment:
  sdk: ^3.2.5

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
  # For benchmarks
  formula_parser: ^2.0.1
  math_expressions: ^2.6.0
  math_parser: ^1.5.1
  quds_formula_parser: ^0.0.7