name: eq_parser
description: A lightweight and fast mathematical equation parser with support for functions and variables.
version: 1.0.0
repository: https://github.com/projectitis/eq_parser.git

environment:
  sdk: ^3.2.5

dependencies:

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
